version: "3.9"

services:
  frontend:
    build: .
    container_name: react-frontend
    environment:
      - REACT_APP_FLASK_SERVER=http://localhost:5000
    ports:
      - "3000:3000"
    restart: always
